version: '3'
services:
  frontend:
    build:
      context: ./imgdet-frtend
    ports:
      - '5173:5173'
    depends_on:
      - backend

  backend:
    build:
      context: ./image-det-backend
    ports:
      - '5000:5000'
